name: Collect and Deploy
on: [workflow_dispatch]
permissions:
  contents: write
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    env:
      GH_TOKEN: ${{ github.token }}
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          mkdir build
          bash collect.sh
          bash filter.sh
          cp -r filter build

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.extension-name }}.extension.wasm
          path: build/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
