name: Collect and Deploy
on:
  workflow_dispatch:
    inputs:
       days:
         description: 'How many days going back'
         type: string
         default: '0'
         required: false

permissions:
  contents: write
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    env:
      GH_TOKEN: ${{ github.token }}
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          mkdir build
          export DAYS=${{ inputs.days }} 
          bash collect.sh
          bash filter.sh
          cp filter/* build
          cp install.sh build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          single-commit: true
          commit-message: 'Deploy latests packages @ duckdb/duckdb@${{ env.HASH }} :duck:'
